version: "3"

services:
  go-transcode:
    build: .
    container_name: go-transcode
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./streams.yaml:/app/streams.yaml
    command: serve -d
